version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: limbic
      POSTGRES_USER: limbic_user
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432
  testDb:
    image: postgres:13
    restart: always
    volumes:
      - ./test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: limbic_test
      POSTGRES_USER: limbic_test_user
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5433:5432
